// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"postfeed/internal/domain"

	"github.com/google/uuid"
)

type CommentConnection struct {
	Nodes      []*domain.Comment `json:"nodes"`
	NextCursor *uuid.UUID        `json:"nextCursor,omitempty"`
	TotalCount int32             `json:"totalCount"`
}

type CreateCommentInput struct {
	PostID   uuid.UUID  `json:"postId"`
	ParentID *uuid.UUID `json:"parentId,omitempty"`
	Body     string     `json:"body"`
}

type CreatePostInput struct {
	Body            string `json:"body"`
	CommentsEnabled *bool  `json:"commentsEnabled,omitempty"`
}

type Mutation struct {
}

type PostConnection struct {
	Nodes      []*domain.Post `json:"nodes"`
	NextCursor *uuid.UUID     `json:"nextCursor,omitempty"`
	TotalCount int32          `json:"totalCount"`
}

type Query struct {
}
