// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/posts/types/interface.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/posts/types/interface.go -destination=./internal/services/mocks/mockPostsService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "postfeed/internal/domain"
	types "postfeed/internal/services/posts/types"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPostsService is a mock of PostsService interface.
type MockPostsService struct {
	ctrl     *gomock.Controller
	recorder *MockPostsServiceMockRecorder
	isgomock struct{}
}

// MockPostsServiceMockRecorder is the mock recorder for MockPostsService.
type MockPostsServiceMockRecorder struct {
	mock *MockPostsService
}

// NewMockPostsService creates a new mock instance.
func NewMockPostsService(ctrl *gomock.Controller) *MockPostsService {
	mock := &MockPostsService{ctrl: ctrl}
	mock.recorder = &MockPostsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostsService) EXPECT() *MockPostsServiceMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockPostsService) CreatePost(ctx context.Context, input types.CreatePostInput) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, input)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostsServiceMockRecorder) CreatePost(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostsService)(nil).CreatePost), ctx, input)
}

// GetPost mocks base method.
func (m *MockPostsService) GetPost(ctx context.Context, id uuid.UUID) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", ctx, id)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockPostsServiceMockRecorder) GetPost(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockPostsService)(nil).GetPost), ctx, id)
}

// ListPosts mocks base method.
func (m *MockPostsService) ListPosts(ctx context.Context, input types.ListPostsInput) ([]domain.Post, domain.Cursor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPosts", ctx, input)
	ret0, _ := ret[0].([]domain.Post)
	ret1, _ := ret[1].(domain.Cursor)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPosts indicates an expected call of ListPosts.
func (mr *MockPostsServiceMockRecorder) ListPosts(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPosts", reflect.TypeOf((*MockPostsService)(nil).ListPosts), ctx, input)
}

// SetCommentsEnabled mocks base method.
func (m *MockPostsService) SetCommentsEnabled(ctx context.Context, postID, userID uuid.UUID, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCommentsEnabled", ctx, postID, userID, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCommentsEnabled indicates an expected call of SetCommentsEnabled.
func (mr *MockPostsServiceMockRecorder) SetCommentsEnabled(ctx, postID, userID, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCommentsEnabled", reflect.TypeOf((*MockPostsService)(nil).SetCommentsEnabled), ctx, postID, userID, enabled)
}
