package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"postfeed/internal/domain"
	"postfeed/internal/graph/model"
	"postfeed/internal/services/auth"
	commentsServiceTypes "postfeed/internal/services/comments/types"
	postsServiceTypes "postfeed/internal/services/posts/types"

	"github.com/google/uuid"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*domain.Post, error) {
	postID, err := r.PostsService.CreatePost(ctx, postsServiceTypes.CreatePostInput{
		UserID:          auth.UserIDFromCtx(ctx),
		Body:            input.Body,
		CommentsEnabled: *input.CommentsEnabled,
	})
	if err != nil {
		return nil, toGQLError(err)
	}

	post, err := r.PostsService.GetPost(ctx, postID)
	if err != nil {
		return nil, toGQLError(fmt.Errorf("r.PostsService.GetPost: %w", err))
	}

	return post, nil
}

// SetPostCommentsEnabled is the resolver for the setPostCommentsEnabled field.
func (r *mutationResolver) SetPostCommentsEnabled(ctx context.Context, postID uuid.UUID, enabled bool) (*domain.Post, error) {
	err := r.PostsService.SetCommentsEnabled(ctx, postID, auth.UserIDFromCtx(ctx), enabled)
	if err != nil {
		return nil, toGQLError(err)
	}

	post, err := r.PostsService.GetPost(ctx, postID)
	if err != nil {
		return nil, toGQLError(fmt.Errorf("r.PostsService.GetPost: %w", err))
	}

	return post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*domain.Comment, error) {
	parentId := uuid.NullUUID{}
	if input.ParentID != nil {
		parentId.Valid = true
		parentId.UUID = *input.ParentID
	}

	id, err := r.CommentsService.CreateComment(ctx, commentsServiceTypes.CreateCommentInput{
		PostID:   input.PostID,
		ParentID: parentId,
		UserID:   auth.UserIDFromCtx(ctx),
		Body:     input.Body,
	})
	if err != nil {
		return nil, toGQLError(err)
		//switch {
		//case errors.Is(err, commentsServiceTypes.ErrPostNotFound):
		//	return nil, gqlError(
		//		"Non-existing Post",
		//		"NOT_FOUND",
		//	)
		//case errors.Is(err, commentsServiceTypes.ErrCommentNotFound):
		//	return nil, gqlError(
		//		"Non-existing parent Comment",
		//		"NOT_FOUND",
		//	)
		//case errors.Is(err, commentsServiceTypes.ErrCommentsDisabled):
		//	return nil, gqlError(
		//		"Post commenting is disabled",
		//		"OPERATION_NOT_PERMITTED",
		//	)
		//default:
		//	return nil, fmt.Errorf("r.CommentsService.CreateComment: %w", err)
		//}
	}

	comment, err := r.CommentsService.GetComment(ctx, id)
	if err != nil {
		return nil, toGQLError(fmt.Errorf("r.CommentsService.CreateComment: %w", err))
	}

	return comment, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
