package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"postfeed/internal/domain"
	"postfeed/internal/graph/model"
	postsServiceTypes "postfeed/internal/services/posts/types"

	"github.com/google/uuid"
)

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first *int32, after *uuid.UUID) (*model.PostConnection, error) {
	limit := *first

	posts, nextCursor, err := r.PostsService.ListPosts(ctx, postsServiceTypes.ListPostsInput{
		Limit:      int64(limit),
		CursorNext: after,
	})
	if err != nil {
		return nil, toGQLError(fmt.Errorf("r.PostsService.ListPosts: %w", err))
	}

	nodes := make([]*domain.Post, 0, len(posts))
	for _, post := range posts {
		nodes = append(nodes, &post)
	}

	return &model.PostConnection{
		Nodes:      nodes,
		NextCursor: nextCursor.Next,
		TotalCount: 0,
	}, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id uuid.UUID) (*domain.Post, error) {
	post, err := r.PostsService.GetPost(ctx, id)
	if err != nil {
		return nil, toGQLError(fmt.Errorf("r.PostsService.GetPost: %w", err))
	}

	return post, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
