package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"postfeed/internal/domain"

	"github.com/google/uuid"
)

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID uuid.UUID) (<-chan *domain.Comment, error) {
	ch := make(chan *domain.Comment, 1)
	events, unsubscribe := r.PubSub.Subscribe(ctx, postID)

	go func() {
		defer close(ch)
		defer unsubscribe()

		for {
			select {
			case <-ctx.Done():
				return
			case comment, ok := <-events:
				if !ok {
					return
				}
				select {
				case ch <- comment:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return ch, nil
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
