package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"postfeed/internal/domain"
	"postfeed/internal/graph/model"
	commentsServiceTypes "postfeed/internal/services/comments/types"
	"time"

	"github.com/google/uuid"
)

// ParentID is the resolver for the parentId field.
func (r *commentResolver) ParentID(ctx context.Context, obj *domain.Comment) (*uuid.UUID, error) {
	if obj.ParentID.Valid {
		return &obj.ParentID.UUID, nil
	}

	return nil, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *commentResolver) CreatedAt(ctx context.Context, obj *domain.Comment) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *domain.Comment, first *int32, after *uuid.UUID) (*model.CommentConnection, error) {
	limit := *first
	comments, nextCursor, err := r.CommentsService.ListReplies(ctx, commentsServiceTypes.ListRepliesInput{
		ParentID:   obj.ID,
		CursorNext: after,
		Limit:      int64(limit),
	})
	if err != nil {
		return nil, toGQLError(fmt.Errorf("r.CommentsService.ListReplies: %w", err))
	}

	nodes := make([]*domain.Comment, 0, len(comments))
	for _, comment := range comments {
		nodes = append(nodes, &comment)
	}

	return &model.CommentConnection{
		Nodes:      nodes,
		NextCursor: nextCursor.Next,
		TotalCount: 0,
	}, nil
}

// RepliesCount is the resolver for the repliesCount field.
func (r *commentResolver) RepliesCount(ctx context.Context, obj *domain.Comment) (int32, error) {
	return 0, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *postResolver) CreatedAt(ctx context.Context, obj *domain.Post) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *postResolver) UpdatedAt(ctx context.Context, obj *domain.Post) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *domain.Post, first *int32, after *uuid.UUID) (*model.CommentConnection, error) {
	limit := *first
	comments, nextCursor, err := r.CommentsService.ListComments(ctx, commentsServiceTypes.ListCommentsInput{
		PostID:     obj.ID,
		CursorNext: after,
		Limit:      int64(limit),
	})
	if err != nil {
		return nil, toGQLError(fmt.Errorf("r.CommentsService.ListComments: %w", err))
	}

	nodes := make([]*domain.Comment, 0, len(comments))
	for _, comment := range comments {
		nodes = append(nodes, &comment)
	}

	return &model.CommentConnection{
		Nodes:      nodes,
		NextCursor: nextCursor.Next,
		TotalCount: 0,
	}, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

type (
	commentResolver struct{ *Resolver }
	postResolver    struct{ *Resolver }
)
